language: node_js
node_js:
  - "12"
services: xvfb
branches:
  only:
    - master
cache:
  directories:
    - "./Server/node_modules"
before_install:
  - cd Server
install:
  - npm ci
script:
  - npm test
